id = "depsdev-extension"
name = "DepsDev Extension"
description = "Toy extension"
version = "0.1.0"
schema_version = 1
authors = ["Saahitya E <saahitya.e@gmail.com>"]
repository = "https://github.com/saahityaedams/depsdev-extension"

[slash_commands.depsdev-dump]
description = "dumps deps info"
requires_argument = false
